# SNP Grid

Access the SNP data stored in [BigQuery](https://cloud.google.com/bigquery/docs/).

## Import the libraries used in this tutorial

In [1]:
from google.cloud import bigquery
import pandas

## Initialize a client

In [2]:
client = bigquery.Client(location="us-east1",  project="jax-human-t2d-cube-ctl")
print("Client creating using default project: {}".format(client.project))

Client creating using default project: jax-human-t2d-cube-ctl

To explicitly specify a project when constructing the client, set the `project` parameter:

## Run a query to data frame

In [3]:
query = """
    SELECT strain_id, strain_name, ingestion_datetime
      FROM `jax-human-t2d-cube-ctl.mouse_snp.strain_info`
"""
query_job = client.query(query)  
df = query_job.to_dataframe()
df

               strain_id                    strain_name  ingestion_datetime
0    5339200464743804876        B6.PWD-Chr4:B6.PWD-Chr4 2020-08-05 08:46:00
1    8963554149931484877    C57BL/10ScSnJ:C57BL/10ScSnJ 2020-08-05 08:46:00
2    4844769121938721340              AXB3/Pgn:AXB3/Pgn 2020-08-05 08:46:00
3    5164075384704033967  ILSXISS24/TejJ:ILSXISS24/TejJ 2020-08-05 08:46:00
4    9034619123774177361          BXD55/RwwJ:BXD55/RwwJ 2020-08-05 08:46:00
..                   ...                            ...                 ...
572  1020161132669594088            BXD27/TyJ:BXD27/TyJ 2020-08-05 08:46:00
573  6539329622198673314              SOD1/EiJ:SOD1/EiJ 2020-08-05 08:46:00
574  4525693028011200306  ILSXISS46/TejJ:ILSXISS46/TejJ 2020-08-05 08:46:00
575  5774793902071078057                DLS/LeJ:DLS/LeJ 2020-08-05 08:46:00
576  5721347342123961005        BXD65a/RwwJ:BXD65a/RwwJ 2020-08-05 08:46:00

[577 rows x 3 columns]

## Run SNP query

In [4]:
# Define the query
query = """
   SELECT chr, start_position, rs, strain_id, strain_name, genotyp,
          imputed_flag, percent_impluted, percent_missing
    FROM `jax-human-t2d-cube-ctl.mouse_snp.chr6_flat` 
    LIMIT 1000
"""
query_job = client.query(query)  
df = query_job.to_dataframe()
df

,chr,start_position,rs,strain_id,strain_name,genotyp,imputed_flag,percent_impluted,percent_missing
0,6,110002640,rs29877327,5245350778736364583,129P2/OlaHsd:129P2/OlaHsd,A,0,89.8,3.6
1,6,110002640,rs29877327,7681566451879352201,C57L/J:C57L/J,A,0,89.8,3.6
2,6,110002640,rs29877327,6958038404446949245,NZO/HlLtJ:NZO/HlLtJ,A,0,89.8,3.6
3,6,110002640,rs29877327,814856115666740427,NZB/BlNJ:NZB/BlNJ,A,0,89.8,3.6
4,6,110002640,rs29877327,7937957394800611869,C57BL/10J:C57BL/10J,A,0,89.8,3.6
...,...,...,...,...,...,...,...,...,...
995,6,110002193,rs212987900,4174357032238806204,CC074/Unc:CC074/Unc,NA,0,89.9,3.6
996,6,110002193,rs212987900,917260239129299322,QSi5:QSi5,NA,0,89.9,3.6
997,6,110002193,rs212987900,3167128218464671366,PAHARI/EiJ:PAHARI/EiJ,NA,0,89.9,3.6
998,6,110002193,rs212987900,5128392437525108904,CC035/Unc:CC035/Unc,NA,0,89.9,3.6
999,6,110002354,rs214047193,9091799938072091109,NU/J:NU/J,NA,0,89.9,3.6